In [2]:
#API connection and dependency install
import os
from flipside import Flipside
from dotenv import find_dotenv, load_dotenv
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Confirm and define dotenv path
dotenv_path = find_dotenv()
print(f"Loading .env from: {dotenv_path}")

#load env data from path
load_dotenv(dotenv_path, override=True)

#store API_KEY from dotenv file
import os
API_KEY = os.getenv("FLIP_API_KEY")
# print(f"API Key loaded: {API_KEY}")

#instantiate flipside client
flipside = Flipside(API_KEY, "https://api-v2.flipsidecrypto.xyz")

Loading .env from: c:\Users\savan\Desktop\portfolio_repo\arb_airdrop\.env

Fact_blocks - individal block within chain

In [11]:
sql ="""
    select * from arbitrum.core.fact_blocks limit 10000
"""
fact_blocks = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = fact_blocks.columns
rows = fact_blocks.rows
fact_blocks_df = pd.DataFrame(rows, columns=columns)

# see df head
display(fact_blocks_df.head())

,block_number,block_hash,block_timestamp,network,tx_count,size,miner,extra_data,parent_hash,gas_used,...,state_root,transactions_root,logs_bloom,fact_blocks_id,inserted_timestamp,modified_timestamp,blockchain,hash,block_header_json,__row_index
0,60787381,0x9ca854434ade59ffe2c9018b9123c6089368e3a0924b...,2023-02-14T07:57:59.000Z,mainnet,3,2058,0xa4b000000000000000000073657175656e636572,0x9cc3d71f8f0766002a31932e45554352d1a09ce5440f...,0x6f8ad6bf13ee1ea8b423b06d8c7e30dc088a6fbbe5c1...,1527004,...,0xd8d310869909656d43ca2d8f9cb0cfb10f189158472a...,0xe7e63ff341fb748f7cf00338287ade8c40652742a7f8...,0x00000000000000004100000000004000000000000000...,75da6a9c8d5872046265fe4fbcab372f,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,arbitrum,0x9ca854434ade59ffe2c9018b9123c6089368e3a0924b...,"{'baseFeePerGas': 100000000, 'difficulty': 1, ...",0
1,60787283,0xdd7238b3d7b1b9976d86166967450437ab483ec4a509...,2023-02-14T07:57:27.000Z,mainnet,2,1298,0xa4b000000000000000000073657175656e636572,0x9cc3d71f8f0766002a31932e45554352d1a09ce5440f...,0x0bf1d45e4fc42e5c5a074522bc9ecb3ee68c59a1d8eb...,1049327,...,0x22a2887c16ea08b6b3445d0faf588d792964d1d74370...,0xe0db16814e4e1c8aaffab626232dc72a2be6161814d3...,0x00000100000000000000000000000000004000000000...,8a7c9662bd5685abba02422ac10e0a48,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,arbitrum,0xdd7238b3d7b1b9976d86166967450437ab483ec4a509...,"{'baseFeePerGas': 100000000, 'difficulty': 1, ...",1
2,60801117,0xc26a4ede88521fa1cdf6474654cceac74210f8ea9e6f...,2023-02-14T08:57:01.000Z,mainnet,4,2968,0xa4b000000000000000000073657175656e636572,0x7b0e6a654802cb37fc3d224848ff3490ffca2d011e61...,0xb16c6de43747b1aa741bb9b1b80ecc4db789973df73d...,2632207,...,0x05a901fe01018c67848ff1cfb3e42ee8661b0dbb0927...,0x32452235fb3caf6dc785d6c9de5c6f2fdf48ec3373e1...,0x0000a000000000000000800010000000000000001000...,9cc23f7346ed2757d203f30f5f83bc56,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,arbitrum,0xc26a4ede88521fa1cdf6474654cceac74210f8ea9e6f...,"{'baseFeePerGas': 100000000, 'difficulty': 1, ...",2
3,60787304,0x92ca6fa3b6c7e17e9a7d8035aaab9c34b06c32339d0e...,2023-02-14T07:57:34.000Z,mainnet,2,1593,0xa4b000000000000000000073657175656e636572,0x9cc3d71f8f0766002a31932e45554352d1a09ce5440f...,0x3e7f81bc0ad1380d5bae8bef05b7950cd7ce219fb55e...,751518,...,0xda6d63332876688ece72ec00acad8636bd1843b9f1d0...,0x4824bb49a86ed9fa31612ab37bddaaa956b0f1c8bdf1...,0x02000080000000000001000000100000000000000000...,a360ecb5b024e76fc3dd3a3ffe0edbb3,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,arbitrum,0x92ca6fa3b6c7e17e9a7d8035aaab9c34b06c32339d0e...,"{'baseFeePerGas': 100000000, 'difficulty': 1, ...",3
4,103054757,0x7fef70ae20da30b9e7895011ed14f12c796c9e95329d...,2023-06-20T10:19:52.000Z,mainnet,4,1573,0xa4b000000000000000000073657175656e636572,0x7e3b8821f3faa46673aa781923a65b43219ab6753827...,0x09170fa047428b5970401c54c6f38f5b29e52bfeb81f...,1177553,...,0x594cc537aab8145af800db6e7594a35fbc2641c53d82...,0x209e022f2bb9c8400ae292c6a83c0a384b700012ec09...,0x00000000000000000000000000000000000000000000...,768677e087c313b5727c190418018784,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,arbitrum,0x7fef70ae20da30b9e7895011ed14f12c796c9e95329d...,"{'baseFeePerGas': 100000000, 'difficulty': 1, ...",4

fact_transaction - transactions within a block

In [13]:
sql ="""
    select * from arbitrum.core.fact_transactions limit 10000
"""
fact_transactions = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = fact_transactions.columns
rows = fact_transactions.rows
fact_transactions_df = pd.DataFrame(rows, columns=columns)

# see df head
display(fact_transactions_df.head())

,block_number,block_timestamp,tx_hash,from_address,to_address,origin_function_signature,value,value_precise_raw,value_precise,tx_fee,...,r,s,v,fact_transactions_id,inserted_timestamp,modified_timestamp,block_hash,status,position,__row_index
0,138435807,2023-10-07T14:21:43.000Z,0xbd32765e6f5d8abcccafc0cc9b59fe7b153de9d4327d...,0x9a4cfeaff8ae230b63b78036fb424a9d3d104bac,0xbf22f0f184bccbea268df387a49ff5238dd23e40,0x1114cd2a,0.004161,4160564015184040,0.00416056401518404,0.000074,...,0xe1452a1aa02f4c0edb5a2dda67bf652b0d958b28f7ed...,0x7d662500231d5566add01e2cc3ff960720137971809b...,0x0,672ba559d472c8c29c40273715226465,2023-12-06T15:42:47.419Z,2023-12-06T15:42:47.419Z,0x018a19214fee7c74f79aaa309587da3abb4d59f4d120...,SUCCESS,1,0
1,138458740,2023-10-07T15:58:15.000Z,0x1a337823c9935dac65d859115a8954e63fdd01eed477...,0x00000000000000000000000000000000000a4b05,0x00000000000000000000000000000000000a4b05,0x6bf6a42d,0.000000,0,0,0.000000,...,0x0,0x0,0x0,6e9038168b0e481e845f64158bda5544,2023-12-06T15:42:47.419Z,2023-12-06T15:42:47.419Z,0xbed0fac323d72ffd9b0e678a0ecc92454d29bec09234...,SUCCESS,0,1
2,138547366,2023-10-07T22:29:11.000Z,0x5010a6c76f4b1969352830189a339002109159662ca0...,0x21c3de23d98caddc406e3d31b25e807addf33633,0xd56e4eab23cb81f43168f9f45211eb027b9ac7cc,0xb143044b,0.000000,0,0,0.000052,...,0xc57a6001f75692a7f597da2d54f0d03094cc4a335a0a...,0x10368b663d27c4d2cbd4d20696b0a9f4264565437c6f...,0x14986,8048f3bd5ac1c16dce96d0a241a3e994,2023-12-06T15:42:47.419Z,2023-12-06T15:42:47.419Z,0xf579fb90c768f8d0c8fe6f1113b3a39ee2df919c64c6...,SUCCESS,1,2
3,138263697,2023-10-07T01:58:12.000Z,0x15e4f218da7330407ffd77e6bd98117b73b7de22537d...,0x57014ee84cecb5d58e1d94f73680936c9cc4a785,0x87da6930626fe0c7db8bc15587ec0e410937e5dc,0xb51d0534,0.000000,0,0,0.000023,...,0xc86afb9b3848b7a7bba953619535650cee8585075b15...,0x7f7bf78bd17272c8cf3b154c1539b34e7aa1f2d878f9...,0x1,36ecce6e9453594f842d717fd64bb10d,2023-12-06T15:42:47.419Z,2023-12-06T15:42:47.419Z,0xcb95539b5fa5595ff8c2747631f8cb49c28d9db4eb3b...,SUCCESS,2,3
4,138382142,2023-10-07T10:35:45.000Z,0x46ea73a4f41645088810dd5625c6a595074ca704562f...,0xd600897d5f04cad808f1722b71b4c40068ee3a6e,0x789fc99093b09ad01c34dc7251d0c89ce743e5a4,0x56781388,0.000000,0,0,0.000022,...,0x9bf56e2ab198193dbf380a2a740b3276cc8eb4c51298...,0x141c25e2747746203d38235c008ed46de0274f4b9e48...,0x1,cd1e06395b04f70da3c3bc20da58b632,2023-12-06T15:42:47.419Z,2023-12-06T15:42:47.419Z,0xb9a09a0156e1d42a9c4854302b131ee2bce553a55828...,SUCCESS,1,4

fact_traces - tracing interanal EVM calls within transactions

In [14]:
sql ="""
    select * from arbitrum.core.fact_traces limit 10000
"""
fact_traces = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = fact_traces.columns
rows = fact_traces.rows
fact_traces_df = pd.DataFrame(rows, columns=columns)

# see df head
display(fact_traces_df.head())

,block_number,block_timestamp,tx_hash,tx_position,trace_index,from_address,to_address,input,output,type,...,revert_reason,tx_succeeded,identifier,data,tx_status,trace_status,fact_traces_id,inserted_timestamp,modified_timestamp,__row_index
0,26080768,2022-09-23T02:27:25.000Z,0x80a2337e67c7eb3e3907eb12d66dce810982c3cf1cef...,1,37,0x1e0fd2cc7329ddf6bda35f85579e1bc2996db0d9,0x489ee077994b6658eafa855c308275ead8097c4a,0xdf73a267,0x00000000000000000000000000000000000000000000...,STATICCALL,...,None,True,STATICCALL_11_0_2_5,{'from': '0x1e0fd2cc7329ddf6bda35f85579e1bc299...,SUCCESS,SUCCESS,d5f20a68550fb87fbcc298e30384855e,2024-09-10T20:53:37.290Z,2024-09-10T20:53:37.290Z,0
1,26102429,2022-09-23T04:58:47.000Z,0x5ec26d30f357498dbd0b66b86ee845998e0a508050e4...,1,50,0x891200056d8109c0413e8960f1d1f45c764c9e5b,0x45cb6ecd6a22193bb95ab4b3acf0ca9638f7a6aa,0x1a686502,0x00000000000000000000000000000000000000000000...,STATICCALL,...,None,True,STATICCALL_0_3_0_0_3,{'from': '0x891200056d8109c0413e8960f1d1f45c76...,SUCCESS,SUCCESS,54d7f1004b7050015c721f7017dcdaf6,2024-09-10T20:53:37.290Z,2024-09-10T20:53:37.290Z,1
2,26102030,2022-09-23T04:56:02.000Z,0xafb5617c4ac6ed11712fca7ea9a51c2561ee83f428bc...,1,234,0xf3d00a2559d84de7ac093443bcaada5f4ee4165c,0xb7f24e34938d69d12f16bdba0c81756a3464a43c,0x156e29f6000000000000000000000000408b0903a56e...,0x,DELEGATECALL,...,None,True,DELEGATECALL_0_0_85_0,{'from': '0xf3d00a2559d84de7ac093443bcaada5f4e...,SUCCESS,SUCCESS,1b4a7aad361e72150eea13a209ce4c03,2024-09-10T20:53:37.290Z,2024-09-10T20:53:37.290Z,2
3,26171047,2022-09-23T11:56:14.000Z,0xb912d9dcf8d9af2c7d1d02b71f329590f06ca84e8889...,1,34,0xd2d1162512f927a7e282ef43a362659e4f2a728f,0x35247165119b69a40edd5304969560d0ef486921,0x23b872dd000000000000000000000000ad1819cc1a6d...,0x00000000000000000000000000000000000000000000...,CALL,...,None,True,CALL_8_0,{'from': '0xd2d1162512f927a7e282ef43a362659e4f...,SUCCESS,SUCCESS,1ec9dec2b2e4f0a9c6fdf987659714aa,2024-09-10T20:53:37.290Z,2024-09-10T20:53:37.290Z,3
4,26217148,2022-09-23T15:34:34.000Z,0x60256350f3ece36334d9c69f161bb95996d00c072af4...,1,81,0x4521916972a76d5bfa65fb539cf7a0c2592050ac,0x0d7459241c71cc840d95f98c937a8687be2dc95c,0xce4c18de000000000000000000000000000000000000...,0x00000000000000000000000000000000000000058ed7...,DELEGATECALL,...,None,True,DELEGATECALL_0_3_4_0_0_0,{'from': '0x4521916972a76d5bfa65fb539cf7a0c259...,SUCCESS,SUCCESS,fbb1ecf54a1cc1f3282ff92c420a0d1d,2024-09-10T20:53:37.290Z,2024-09-10T20:53:37.290Z,4

Fact_event_logs - event emitted by smart contract within transaction

In [15]:
sql ="""
    select * from arbitrum.core.fact_event_logs limit 10000
"""
fact_event_logs = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = fact_event_logs.columns
rows = fact_event_logs.rows
fact_event_logs_df = pd.DataFrame(rows, columns=columns)

# see df head
display(fact_event_logs_df.head())

,block_number,block_timestamp,tx_hash,event_index,contract_address,topics,topic_0,topic_1,topic_2,topic_3,...,origin_from_address,origin_to_address,origin_function_signature,tx_succeeded,fact_event_logs_id,inserted_timestamp,modified_timestamp,tx_status,_log_id,__row_index
0,86524323,2023-05-02T12:18:27.000Z,0x71e35d86ff867513147b3aac136f311cb996ee1b7817...,9,0xbbbd01326050c2992cacbef28810c760727ebc40,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...,0x000000000000000000000000bb4528a1e36f6a14c7a6...,0x0000000000000000000000001111111254eeb25477b6...,None,...,0x266ad5b7efd14fc42343d6ac3ec820b38248acc0,0x1111111254eeb25477b68fb85ed929f73a960582,0x12aa3caf,True,4a9e6f941b7a394203d9c249158b2e99,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,SUCCESS,0x71e35d86ff867513147b3aac136f311cb996ee1b7817...,0
1,86378530,2023-05-02T02:00:22.000Z,0x0a59f15a070c55d2d51fde8c8aa0724caf9137bbb209...,52,0x09e18590e8f76b6cf471b3cd75fe1a1a9d2b2c2b,[0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b...,0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2...,0x00000000000000000000000009e18590e8f76b6cf471...,0x000000000000000000000000c873fecbd354f5a56e00...,None,...,0xb3f3a676c87c0ea44c8db20cd46c1f6e7bec3d5c,0x5845696f6031bfd57b32e6ce2ddea19a486fa5e5,0x441a3e70,True,1943f3948c1ada67c308d87be322931f,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,SUCCESS,0x0a59f15a070c55d2d51fde8c8aa0724caf9137bbb209...,1
2,86521275,2023-05-02T12:05:53.000Z,0x637da45192223ac509cd066da2740760b722f180dd60...,87,0x912ce59144191c1204e64559fe8253a0e49e6548,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...,0x00000000000000000000000009e18590e8f76b6cf471...,0x000000000000000000000000a025035ece3034ab5c41...,None,...,0xc3317df03fde8f4d098c3be48a8603c00e3841af,0xd115fc5894e85abedbc6a4efdc818849123739ec,0x092b823e,True,28ef2ca3e08f3078d45482affbe74b6d,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,SUCCESS,0x637da45192223ac509cd066da2740760b722f180dd60...,2
3,86517259,2023-05-02T11:49:18.000Z,0xdb1618204731bf959d712b93fcbb6c11066e9356b169...,15,0x912ce59144191c1204e64559fe8253a0e49e6548,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...,0x0000000000000000000000004e4bbacbbbe2b1d77509...,0x0000000000000000000000000ff95912b841c7359123...,None,...,0x1cbf69e47ed7181332bb20df69c51ffd755d46c0,0x1b02da8cb0d097eb8d57a175b88c7d8b47997506,0x7ff36ab5,True,c8ea77e0b94236815c961fc8dd3164e6,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,SUCCESS,0xdb1618204731bf959d712b93fcbb6c11066e9356b169...,3
4,86351019,2023-05-02T00:01:10.000Z,0x37ed3d7c179002f9bba038603f0da3f8afe96f634628...,103,0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...,0x0000000000000000000000008db6cf8e8ec31fcddb9c...,0x0000000000000000000000003a5162c694aeb1ee73f5...,None,...,0xee98b917cbe32ac8d62301d6fe6421a1d1be601a,0x56a029ecb9e88ba497cc55eb5c2c389a38bbbd53,0x03040178,True,b14759d89e8f60d90e13f395862319b6,2000-01-01T00:00:00.000Z,2000-01-01T00:00:00.000Z,SUCCESS,0x37ed3d7c179002f9bba038603f0da3f8afe96f634628...,4

fact_decoded_event_log - Decoded events log table - but deprecated per dbt

In [18]:
sql ="""
    select * from arbitrum.core.fact_decoded_event_logs limit 10000
"""
fact_decoded_event_logs = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = fact_decoded_event_logs.columns
rows = fact_decoded_event_logs.rows
fact_decoded_event_logs_df = pd.DataFrame(rows, columns=columns)

# see df head
display(fact_decoded_event_logs_df.head())

,block_number,block_timestamp,tx_hash,event_index,contract_address,event_name,decoded_log,full_decoded_log,fact_decoded_event_logs_id,inserted_timestamp,modified_timestamp,__row_index
0,411414,2021-09-11T14:08:46.000Z,0x184f27f3d24e8de538f7d16ee1c61cc8ae40b9cb032c...,4,0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9,Approval,{'owner': '0x88cbf433471a0cd8240d2a12354362988...,{'address': '0xFd086bC7CD5C481DCC9C85ebE478A1C...,175a2a9bf9508792fe179c2fcd63e354,2023-12-11T19:07:12.069Z,2023-12-11T19:07:12.069Z,0
1,376768,2021-09-11T03:38:50.000Z,0xf4b19c5cf4bd623008333ceda6b47d9ec06911032a79...,0,0x70df9dd83be2a9f9fcc58dd7c00d032d007b7859,Transfer,{'from': '0xfc87d702139be505715a79c636a80fc092...,{'address': '0x70Df9Dd83be2a9F9Fcc58Dd7C00d032...,a1ae3c8cd079905beec313e41460560a,2023-12-11T19:07:12.069Z,2023-12-11T19:07:12.069Z,1
2,453963,2021-09-11T22:28:16.000Z,0xb3082e9bd609e07e0e3cc2b6fb5937798f8c3391eab7...,0,0xed3fb761414da74b74f33e5c5a1f78104b188dfc,Approval,{'owner': '0x5a361b634b42b7f1f42273a9ebc7a1ad8...,{'address': '0xeD3fB761414DA74b74F33e5c5a1f781...,e955eb1c3050142cbd04b5c81bdaf9f8,2023-12-11T19:07:12.069Z,2023-12-11T19:07:12.069Z,2
3,448869,2021-09-11T21:33:10.000Z,0x7378a9bef87505eab76d427ed583d62d9e66193ac50f...,4,0x9471d482c51d5539bc4e80c05c0fdc52ca3f9bcf,Swap,"{'amount0In': '120000000000000000', 'amount0Ou...",{'address': '0x9471d482c51d5539BC4e80c05c0Fdc5...,cc960c463788035014611df7da49f461,2023-12-11T19:07:12.069Z,2023-12-11T19:07:12.069Z,3
4,453332,2021-09-11T22:20:03.000Z,0xace380f7a7957e621450c770dfc0c43102c9f82fe98a...,3,0xe3579ed3823846518dc6b51e31360cef6cff189f,Sync,"{'reserve0': '14154349253854397883', 'reserve1...",{'address': '0xE3579ED3823846518dc6B51e31360CE...,29705ab13e318af1b3771319bd53d704,2023-12-11T19:07:12.069Z,2023-12-11T19:07:12.069Z,4

ez_decoded_event_logs

In [19]:
sql ="""
    select * from arbitrum.core.ez_decoded_event_logs limit 10000
"""
ez_decoded_event_logs = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = ez_decoded_event_logs.columns
rows = ez_decoded_event_logs.rows
ez_decoded_event_logs_df = pd.DataFrame(rows, columns=columns)

# see df head
display(ez_decoded_event_logs_df.head())

,block_number,block_timestamp,tx_hash,event_index,contract_address,topics,topic_0,topic_1,topic_2,topic_3,...,tx_succeeded,event_name,full_decoded_log,decoded_log,contract_name,ez_decoded_event_logs_id,inserted_timestamp,modified_timestamp,tx_status,__row_index
0,82725204,2023-04-21T08:54:48.000Z,0x40cc47b47150d91e48529938aaa6c68150a432523477...,11,0x352d8275aae3e0c2404d9f68f6cee084b5beb3dd,[0x8d3ee0df6a4b7e82a7f20a763f1c6826e6176323e65...,0x8d3ee0df6a4b7e82a7f20a763f1c6826e6176323e655...,None,None,None,...,True,SendMsg,{'address': '0x352d8275AAE3e0c2404d9f68f6cEE08...,"{'msgType': 1, 'nonce': 72913}",None,5e6692e434833a56908bceaaa225d8c5,2023-12-12T05:10:36.830Z,2023-12-12T05:10:36.830Z,SUCCESS,0
1,82774927,2023-04-21T12:21:12.000Z,0x13d671716f564d57527033f3b21a9c37adc8e8c8f839...,67,0x82af49447d8a07e3bd95bd0d56f35241523fbab1,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...,0x000000000000000000000000c873fecbd354f5a56e00...,0x000000000000000000000000fe5a433bcee3ac814769...,None,...,True,Transfer,{'address': '0x82aF49447D8a07e3bd95BD0d56f3524...,{'from': '0xc873fecbd354f5a56e00e710b90ef4201d...,Wrapped Ether,c33cbc258093ad5a90d796d8031b7f8e,2023-12-12T05:10:36.830Z,2023-12-12T05:10:36.830Z,SUCCESS,1
2,82612744,2023-04-21T01:04:20.000Z,0x17129b327f431c2b079d82924923d25c490612016e41...,18,0xf1a82bfa7fceb8b8741e7e04a6b8efd348ca6393,[0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c...,0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...,0x000000000000000000000000f1a82bfa7fceb8b8741e...,0x000000000000000000000000fe5a433bcee3ac814769...,None,...,True,Transfer,{'address': '0xF1A82bfA7fCEb8B8741e7E04a6B8EfD...,{'from': '0xf1a82bfa7fceb8b8741e7e04a6b8efd348...,AISHIB,b7f09c2d8b931f280fe2546220f071d8,2023-12-12T05:10:36.830Z,2023-12-12T05:10:36.830Z,SUCCESS,2
3,82835911,2023-04-21T16:34:36.000Z,0xcbff497cd1ba99e66d2711a6f26aee8ca65da528e3fc...,3,0x892785f33cdee22a30aef750f285e18c18040c3e,[0xfb2b592367452f1c437675bed47f5e1e6c25188c17d...,0xfb2b592367452f1c437675bed47f5e1e6c25188c17d7...,None,None,None,...,True,SwapRemote,{'address': '0x892785f33CdeE22A30AEF750F285E18...,"{'amountSD': 1022156229, 'dstFee': 30683, 'pro...",USD Coin (Arb1)-LP,dc41df32d27ca8ecd6ba676ae6a5a2d2,2023-12-12T05:10:36.830Z,2023-12-12T05:10:36.830Z,SUCCESS,3
4,82899819,2023-04-21T21:03:11.000Z,0x2fb5c041ec488e66cfb9db90f7570ed45d08e3a8c917...,9,0x31c91d8fb96bff40955dd2dbc909b36e8b104dde,[0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b...,0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2...,0x0000000000000000000000001501cf2e9afd2624a485...,0x0000000000000000000000001111111254eeb25477b6...,None,...,True,Approval,{'address': '0x31C91D8Fb96BfF40955DD2dbc909B36...,{'owner': '0x1501cf2e9afd2624a485e675427609a19...,Poison.Finance Poison,6f061f1308844f30119768637ef820ac,2023-12-12T05:10:36.830Z,2023-12-12T05:10:36.830Z,SUCCESS,4

In [20]:
display(ez_decoded_event_logs_df["decoded_log"].head())

0                       {'msgType': 1, 'nonce': 72913}
1    {'from': '0xc873fecbd354f5a56e00e710b90ef4201d...
2    {'from': '0xf1a82bfa7fceb8b8741e7e04a6b8efd348...
3    {'amountSD': 1022156229, 'dstFee': 30683, 'pro...
4    {'owner': '0x1501cf2e9afd2624a485e675427609a19...
Name: decoded_log, dtype: object

dim_contracts - all the key contract info

In [28]:
sql ="""
    select * from arbitrum.core.dim_contracts limit 10000
"""
dim_contracts = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = dim_contracts.columns
rows = dim_contracts.rows
dim_contracts_df = pd.DataFrame(rows, columns=columns)

# see df head
print(dim_contracts_df["symbol"].nunique())

127

Creating Token Balance Table - Show the LAtest Token Balance as well as daily

In [ ]:
#Latest Balance

In [ ]:
# Daily Balance OG Approach using event log

sql ="""
-- Create or Replace Table: daily_token_balances

--CREATE OR REPLACE TABLE your_schema.daily_token_balances AS
--Universe of all transfers for arb
WITH erc20_transfers AS (
    SELECT
        el.block_number,
        el.block_timestamp,
        el.contract_address AS token_address,
        el.topic_1 AS from_address,
        el.topic_2 AS to_address,
        CAST(el.data AS NUMBER) AS amount_raw
    FROM arbitrum.core.fact_event_logs el
    JOIN arbitrum.core.dim_contracts tc 
        ON el.contract_address = tc.address
    WHERE el.topic_0 = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'--Only Transfer transactions
        AND el.contract_address = lower('0x912CE59144191C1204E64559FE8253a0e49E6548')
),

-- Split transactions for from and to address, making from address amount values negative, to represent value leaving wallet
all_transfers AS (
    -- From address therefore negative amount_raw
    SELECT 
        DATE_TRUNC('day', block_timestamp) AS date,
        token_address,
        from_address AS wallet_address,
        -amount_raw AS delta_raw
    FROM erc20_transfers
    UNION ALL
    -- To address therefore positive amount_raw
    SELECT 
        DATE_TRUNC('day', block_timestamp) AS date,
        token_address,
        to_address AS wallet_address,
        amount_raw AS delta_raw
    FROM erc20_transfers
),

--Calculate daily balance amount
daily_deltas AS (
    SELECT
        wallet_address,
        token_address,
        date,
        SUM(delta_raw) AS daily_delta_raw
    FROM all_transfers
    GROUP BY wallet_address, token_address, date
),

-- Rolling balance over time
cumulative_balances AS (
    SELECT
        wallet_address,
        token_address,
        date,
        SUM(daily_delta_raw) OVER (
            PARTITION BY wallet_address, token_address
            ORDER BY date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS balance_raw
    FROM daily_deltas
)

SELECT
    cb.wallet_address,
    cb.token_address,
    tc.symbol AS token_symbol,
    tc.decimals,
    cb.date,
    cb.balance_raw,
    cb.balance_raw / POWER(10, tc.decimals) AS balance_adjusted
FROM cumulative_balances cb
JOIN arbitrum.core.dim_contracts tc 
    ON cb.token_address = tc.address
WHERE cb.balance_raw != 0; -- Filter out 0 balances
"""
token_balances = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = token_balances.columns
rows = token_balances.rows
token_balance_logs_df = pd.DataFrame(rows, columns=columns)

# see df head
display(token_balance_logs_df.head())

QueryRunExecutionError: QUERY_RUN_EXECUTION_ERROR: an error has occured while executing your query. errorName=OperationFailedError, errorMessage=Numeric value '0x0000000000000000000000000000000000000000000000034c84011f8f7e0800' is not recognized, errorData={'code': '100038', 'data': {'age': 0, 'queryId': '01bb33e8-0514-7860-3d4f-83030fb109bf', 'sqlState': '22018', 'errorCode': '100038'}, 'name': 'OperationFailedError', 'message': "Numeric value '0x0000000000000000000000000000000000000000000000034c84011f8f7e0800' is not recognized", 'sqlState': '22018'}

In [30]:
# Daily Balance Using ez _token_transfers

sql ="""
-- Create or Replace Table: daily_token_balances

--CREATE OR REPLACE TABLE your_schema.daily_token_balances AS
--Universe of all transfers for arb
WITH erc20_transfers AS (
    SELECT
        tt.block_number,
        tt.block_timestamp,
        tt.contract_address AS token_address,
        tt.from_address,
        tt.to_address,
        tt.amount AS amount_raw
    FROM arbitrum.core.ez_token_transfers tt
    JOIN arbitrum.core.dim_contracts tc 
        ON tt.contract_address = tc.address
    WHERE tt.contract_address = lower('0x912CE59144191C1204E64559FE8253a0e49E6548')
        and tt.amount > 0
),

-- Split transactions for from and to address, making from address amount values negative, to represent value leaving wallet
all_transfers AS (
    -- From address therefore negative amount_raw
    SELECT 
        DATE_TRUNC('day', block_timestamp) AS date,
        token_address,
        from_address AS wallet_address,
        -amount_raw AS delta_raw
    FROM erc20_transfers
    UNION ALL
    -- To address therefore positive amount_raw
    SELECT 
        DATE_TRUNC('day', block_timestamp) AS date,
        token_address,
        to_address AS wallet_address,
        amount_raw AS delta_raw
    FROM erc20_transfers
),

--Calculate daily balance amount
daily_deltas AS (
    SELECT
        wallet_address,
        token_address,
        date,
        SUM(delta_raw) AS daily_delta_raw
    FROM all_transfers
    GROUP BY wallet_address, token_address, date
),

-- Rolling balance over time
cumulative_balances AS (
    SELECT
        wallet_address,
        token_address,
        date,
        SUM(daily_delta_raw) OVER (
            PARTITION BY wallet_address, token_address
            ORDER BY date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS balance_raw
    FROM daily_deltas
)

SELECT
    cb.wallet_address,
    cb.token_address,
    tc.symbol AS token_symbol,
    tc.decimals,
    cb.date,
    cb.balance_raw,
    cb.balance_raw / POWER(10, tc.decimals) AS balance_adjusted
FROM cumulative_balances cb
JOIN arbitrum.core.dim_contracts tc 
    ON cb.token_address = tc.address
WHERE cb.balance_raw != 0; -- Filter out 0 balances
"""
token_balances = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = token_balances.columns
rows = token_balances.rows
token_balance_logs_df = pd.DataFrame(rows, columns=columns)

# see df head
display(token_balance_logs_df.head())

QueryRunExecutionError: QUERY_RUN_EXECUTION_ERROR: an error has occured while executing your query. errorName=QueryResultsTooLarge, errorMessage=The size of the returned query results are too large. Please reduce the number of rows returned. Limit: 1024 MB. Estimated size: 2341 MB., errorData={'resultSizelimitGB': 1024, 'estimatedResultSizeMB': 2341}

In [34]:
# Daily Balance Using ez _token_transfers

sql ="""
WITH airdrop_recipients AS (
    -- Base: wallets that claimed ARB airdrop
    SELECT 
        to_address AS wallet_address,
        block_timestamp AS claim_time,
        amount AS claimed_amount
    FROM arbitrum.core.ez_token_transfers
    WHERE 
        from_address = LOWER('0x67a24CE4321aB3aF51c2D0a4801c3E111D88C9d9')
        AND contract_address = LOWER('0x912CE59144191C1204E64559FE8253a0e49E6548')
        AND amount > 0
),

erc20_transfers AS (
    -- Extract only relevant ERC-20 transfers
    SELECT
        tt.block_number,
        tt.block_timestamp,
        tt.contract_address AS token_address,
        tt.from_address,
        tt.to_address,
        tt.amount AS amount_raw
    FROM arbitrum.core.ez_token_transfers tt
    JOIN arbitrum.core.dim_contracts tc 
        ON tt.contract_address = tc.address
    WHERE tt.contract_address = lower('0x912CE59144191C1204E64559FE8253a0e49E6548')
        and tt.amount > 0
),

filtered_transfers AS (
    -- Join transfers to recipients, apply 30-day limit
    SELECT
        t.block_number,
        t.block_timestamp,
        t.token_address,
        r.wallet_address,
        --handle both from and to transaction for wallet (from gets negative)
        CASE 
            WHEN t.from_address = r.wallet_address THEN -t.amount_raw
            WHEN t.to_address = r.wallet_address THEN t.amount_raw
            ELSE 0 -- Ignore other wallets
        END AS delta_raw
    FROM erc20_transfers t
    JOIN airdrop_recipients r
        ON (t.from_address = r.wallet_address OR t.to_address = r.wallet_address)
        AND t.block_timestamp >= r.claim_time --transfer on or after claim day
        AND t.block_timestamp < TIMESTAMPADD(DAY, 30, r.claim_time) -- transfer within 30 days of claim day
),

aggregated_balances AS (
    -- Aggregate net balances per wallet/token
    SELECT
        wallet_address,
        token_address,
        SUM(delta_raw) AS balance_raw,
        MAX(block_number) AS last_updated_block,
        MAX(block_timestamp) AS last_updated_timestamp
    FROM filtered_transfers
    GROUP BY wallet_address, token_address
    HAVING balance_raw != 0
)

SELECT
    ab.wallet_address,
    ab.token_address,
    tc.symbol AS token_symbol,
    tc.decimals,
    ab.balance_raw,
    ab.balance_raw / POWER(10, tc.decimals) AS balance_adjusted,
    ab.last_updated_block,
    ab.last_updated_timestamp
FROM aggregated_balances ab
JOIN arbitrum.core.dim_contracts tc 
    ON ab.token_address = tc.address;

"""
token_balances = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = token_balances.columns
rows = token_balances.rows
token_balance_logs_df = pd.DataFrame(rows, columns=columns)

# see df head
display(token_balance_logs_df.head())

QueryRunExecutionError: QUERY_RUN_EXECUTION_ERROR: an error has occured while executing your query. errorName=OperationFailedError, errorMessage=Statement reached its statement or warehouse timeout of 900 second(s) and was canceled., errorData={'code': '000630', 'data': {'age': 1, 'queryId': '01bb350e-0514-7800-3d4f-83030fdba847', 'sqlState': '57014', 'errorCode': '000630'}, 'name': 'OperationFailedError', 'message': 'Statement reached its statement or warehouse timeout of 900 second(s) and was canceled.', 'sqlState': '57014'}

This query is correct, but we keep hitting a time out error. Going to further simplify the ez_token_transfers in seperate notebook and run queries in batches to avoid time out.

In [38]:
# Daily Balance Using ez _token_transfers

sql ="""
WITH airdrop_recipients AS (
    SELECT 
        to_address AS wallet_address,
        block_number AS claim_block,
        block_timestamp AS claim_time
    FROM arbitrum.core.ez_token_transfers
    WHERE 
        from_address = LOWER('0x67a24CE4321aB3aF51c2D0a4801c3E111D88C9d9')
        AND contract_address = LOWER('0x912CE59144191C1204E64559FE8253a0e49E6548')
        AND amount > 0
),

filtered_transfers AS (
    -- Use ez_token_transfers (MUCH smaller)
    SELECT
        ett.block_number,
        ett.block_timestamp,
        ett.contract_address AS token_address,
        ett.from_address,
        ett.to_address,
        ett.amount AS amount_raw,
        r.wallet_address,
        r.claim_time
    FROM arbitrum.core.ez_token_transfers ett
    JOIN airdrop_recipients r
        ON (ett.from_address = r.wallet_address OR ett.to_address = r.wallet_address)
        -- Keep only transfers within 30 days window
        AND ett.block_timestamp >= r.claim_time -- post claim date
        AND ett.block_timestamp < TIMESTAMPADD(DAY, 30, r.claim_time) -- pre 30 days after claim date
    -- OPTIONAL: ARB Token only
    WHERE ett.contract_address = LOWER('0x912CE59144191C1204E64559FE8253a0e49E6548')
),

agg_balances AS (
    SELECT
        wallet_address,
        token_address,
        SUM(
            CASE 
                WHEN from_address = wallet_address THEN -amount_raw
                WHEN to_address = wallet_address THEN amount_raw
                ELSE 0
            END
        ) AS balance_raw,
        MAX(block_number) AS last_updated_block,
        MAX(block_timestamp) AS last_updated_timestamp
    FROM filtered_transfers
    GROUP BY wallet_address, token_address
    HAVING balance_raw != 0
)

SELECT
    ab.wallet_address,
    ab.token_address,
--    tc.symbol AS token_symbol,
--    tc.decimals,
    ab.balance_raw,
--    ab.balance_raw / POWER(10, tc.decimals) AS balance_adjusted,
    ab.last_updated_block,
    ab.last_updated_timestamp
FROM agg_balances ab
--JOIN arbitrum.core.dim_contracts tc 
--    ON ab.token_address = tc.address;
"""
token_balances = flipside.query(sql)

#Format and create dataframe from flipside returned query
columns = token_balances.columns
rows = token_balances.rows
token_balance_logs_df = pd.DataFrame(rows, columns=columns)

# see df head
display(token_balance_logs_df.head())

QueryRunExecutionError: QUERY_RUN_EXECUTION_ERROR: an error has occured while executing your query. errorName=OperationFailedError, errorMessage=Statement reached its statement or warehouse timeout of 900 second(s) and was canceled., errorData={'code': '000630', 'data': {'age': 1, 'queryId': None, 'sqlState': '57014', 'errorCode': '000630'}, 'name': 'OperationFailedError', 'message': 'Statement reached its statement or warehouse timeout of 900 second(s) and was canceled.', 'sqlState': '57014'}